name: Validate the massbank records

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - dev
      - main

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Download and unpack MassBank CLI tools
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release download --repo MassBank/MassBank-cli-tools --pattern 'MassBank-cli-tools-*.zip' --dir .scripts
          files=(.scripts/MassBank-cli-tools-*.zip)
          if [ ${#files[@]} -eq 0 ]; then
            echo "No MassBank-cli-tools zip found via gh"
            exit 1
          fi
          for f in "${files[@]}"; do unzip -o "$f" -d .scripts; done
          rm -f .scripts/MassBank-cli-tools-*.zip

      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          distribution: "temurin"
          java-version: "21"

      - name: Run the validating script
        run: bash .scripts/run_validation.sh
